version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
#    volumes:
#      - ./db/conf.d:/etc/mysql/conf.d
#      - ./db/data:/var/lib/mysql
#      - ./db/initdb.d:/docker-entrypoint-initdb.d
#    env_file: .env
    environment:
      MARIADB_DATABASE: memorize
      MARIADB_USER: gt
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - compose_network
volumes:
  mysql-data:
    external: true
#  applications:
#    image: memo/memorize-everything:0.0.1
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    container_name: application
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/memorize
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
#    networks:
#      - compose_network

networks:
  compose_network: