spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/memorize
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
cors:
  originPatterns: http://gwegwe1234.synology.me:3000
